language: python
dist: bionic 

compiler:
  - gcc

os:
  - linux

env:
  global:
    - INSTALL_ROOT=$HOME/install

sudo: required

python:
  - 3.8

matrix:
    fast_finish: true

before_install:
  - export PYTHONPATH=$INSTALL_ROOT/lib/python$TRAVIS_PYTHON_VERSION/site-packages:$INSTALL_ROOT/lib/python$TRAVIS_PYTHON_VERSION/dist-packages:$PYTHONPATH


install:
  #  - pushd ..
  #- git clone --recursive https://github.com/OPM/opm-common.git
  #- mkdir opm-common/build
  #- pushd opm-common/build
  #- cmake .. -DCMAKE_PREFIX_PATH=$INSTALL_ROOT
  #           -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT
  #           -DBUILD_TESTING=OFF
  #           -DBUILD_SHARED_LIBS=ON
  #           -DOPM_ENABLE_PYTHON=ON
  #           -DOPM_INSTALL_PYTHON=ON
  #- make -j4 install
  #- popd # back to opm-common
  #- popd # back to ecl2df
  - pip install -r requirements_dev.txt
  - pip install .

script:
   python -m pytest tests/test*.py -s

